/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VirustotalRouteImport } from './routes/virustotal'
import { Route as ThreatFeedRouteImport } from './routes/threat-feed'
import { Route as ShodanRouteImport } from './routes/shodan'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as KevRouteImport } from './routes/kev'
import { Route as IpDomainRouteImport } from './routes/ip-domain'
import { Route as EmailBreachRouteImport } from './routes/email-breach'
import { Route as DnsReconRouteImport } from './routes/dns-recon'
import { Route as CveSearchRouteImport } from './routes/cve-search'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const VirustotalRoute = VirustotalRouteImport.update({
  id: '/virustotal',
  path: '/virustotal',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatFeedRoute = ThreatFeedRouteImport.update({
  id: '/threat-feed',
  path: '/threat-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ShodanRoute = ShodanRouteImport.update({
  id: '/shodan',
  path: '/shodan',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const KevRoute = KevRouteImport.update({
  id: '/kev',
  path: '/kev',
  getParentRoute: () => rootRouteImport,
} as any)
const IpDomainRoute = IpDomainRouteImport.update({
  id: '/ip-domain',
  path: '/ip-domain',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailBreachRoute = EmailBreachRouteImport.update({
  id: '/email-breach',
  path: '/email-breach',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsReconRoute = DnsReconRouteImport.update({
  id: '/dns-recon',
  path: '/dns-recon',
  getParentRoute: () => rootRouteImport,
} as any)
const CveSearchRoute = CveSearchRouteImport.update({
  id: '/cve-search',
  path: '/cve-search',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cve-search': typeof CveSearchRoute
  '/dns-recon': typeof DnsReconRoute
  '/email-breach': typeof EmailBreachRoute
  '/ip-domain': typeof IpDomainRoute
  '/kev': typeof KevRoute
  '/saved': typeof SavedRoute
  '/shodan': typeof ShodanRoute
  '/threat-feed': typeof ThreatFeedRoute
  '/virustotal': typeof VirustotalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cve-search': typeof CveSearchRoute
  '/dns-recon': typeof DnsReconRoute
  '/email-breach': typeof EmailBreachRoute
  '/ip-domain': typeof IpDomainRoute
  '/kev': typeof KevRoute
  '/saved': typeof SavedRoute
  '/shodan': typeof ShodanRoute
  '/threat-feed': typeof ThreatFeedRoute
  '/virustotal': typeof VirustotalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cve-search': typeof CveSearchRoute
  '/dns-recon': typeof DnsReconRoute
  '/email-breach': typeof EmailBreachRoute
  '/ip-domain': typeof IpDomainRoute
  '/kev': typeof KevRoute
  '/saved': typeof SavedRoute
  '/shodan': typeof ShodanRoute
  '/threat-feed': typeof ThreatFeedRoute
  '/virustotal': typeof VirustotalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/cve-search'
    | '/dns-recon'
    | '/email-breach'
    | '/ip-domain'
    | '/kev'
    | '/saved'
    | '/shodan'
    | '/threat-feed'
    | '/virustotal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/cve-search'
    | '/dns-recon'
    | '/email-breach'
    | '/ip-domain'
    | '/kev'
    | '/saved'
    | '/shodan'
    | '/threat-feed'
    | '/virustotal'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/cve-search'
    | '/dns-recon'
    | '/email-breach'
    | '/ip-domain'
    | '/kev'
    | '/saved'
    | '/shodan'
    | '/threat-feed'
    | '/virustotal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  CveSearchRoute: typeof CveSearchRoute
  DnsReconRoute: typeof DnsReconRoute
  EmailBreachRoute: typeof EmailBreachRoute
  IpDomainRoute: typeof IpDomainRoute
  KevRoute: typeof KevRoute
  SavedRoute: typeof SavedRoute
  ShodanRoute: typeof ShodanRoute
  ThreatFeedRoute: typeof ThreatFeedRoute
  VirustotalRoute: typeof VirustotalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/virustotal': {
      id: '/virustotal'
      path: '/virustotal'
      fullPath: '/virustotal'
      preLoaderRoute: typeof VirustotalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-feed': {
      id: '/threat-feed'
      path: '/threat-feed'
      fullPath: '/threat-feed'
      preLoaderRoute: typeof ThreatFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shodan': {
      id: '/shodan'
      path: '/shodan'
      fullPath: '/shodan'
      preLoaderRoute: typeof ShodanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kev': {
      id: '/kev'
      path: '/kev'
      fullPath: '/kev'
      preLoaderRoute: typeof KevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip-domain': {
      id: '/ip-domain'
      path: '/ip-domain'
      fullPath: '/ip-domain'
      preLoaderRoute: typeof IpDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-breach': {
      id: '/email-breach'
      path: '/email-breach'
      fullPath: '/email-breach'
      preLoaderRoute: typeof EmailBreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns-recon': {
      id: '/dns-recon'
      path: '/dns-recon'
      fullPath: '/dns-recon'
      preLoaderRoute: typeof DnsReconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cve-search': {
      id: '/cve-search'
      path: '/cve-search'
      fullPath: '/cve-search'
      preLoaderRoute: typeof CveSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CveSearchRoute: CveSearchRoute,
  DnsReconRoute: DnsReconRoute,
  EmailBreachRoute: EmailBreachRoute,
  IpDomainRoute: IpDomainRoute,
  KevRoute: KevRoute,
  SavedRoute: SavedRoute,
  ShodanRoute: ShodanRoute,
  ThreatFeedRoute: ThreatFeedRoute,
  VirustotalRoute: VirustotalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
